export const GROUNDROUTING_GET = "groundRouting/GROUNDROUTING_GET";
export const GROUNDROUTING_GET_SUCCESS =
    "groundRouting/GROUNDROUTING_GET_SUCCESS";
export const GROUNDROUTING_GET_ERROR = "groundRouting/GROUNDROUTING_GET_ERROR";
export const GROUNDROUTING_SET = "groundRouting/GROUNDROUTING_SET";
export const GROUNDROUTING_SET_SUCCESS =
    "groundRouting/GROUNDROUTING_SET_SUCCESS";
export const GROUNDROUTING_SET_ERROR = "groundRouting/GROUNDROUTING_SET_ERROR";
