export const LOCATION_USER_SET =  'meta/LOCATION_USER_SET';
export const CONECTION_START = 'meta/CONECTION_START';
export const CONECTION_ERROR = 'meta/CONECTION_ERROR';
export const CONECTION_SUCCESS = 'meta/CONECTION_SUCCESS';
export const CONECTION_CHANGE_URL = 'meta/CONECTION_CHANGE_URL';
export const CONECTION_LOAD_NEIGHBORS = 'meta/CONECTION_LOAD_NEIGHBORS';
export const CONECTION_LOAD_NEIGHBORS_SUCCESS = 'meta/CONECTION_LOAD_NEIGHBORS_SUCCESS';
export const CONECTION_LOAD_HOSTNAME = 'meta/CONECTION_LOAD_HOSTNAME';
export const CONECTION_LOAD_HOSTNAME_SUCCESS = 'meta/CONECTION_LOAD_HOSTNAME_SUCCESS';
export const CONECTION_CHANGE_CURRENT_BASE = 'meta/CONECTION_CHANGE_CURRENT_BASE';

export const CONECTION_SETTINGS = 'meta/CONECTION_SETTINGS';

export const COMMUNITY_SETTINGS_LOAD_SUCCESS = 'meta/COMMUNITY_SETTINGS_LOAD_SUCCESS';

export const AUTH_LOGIN = 'meta/AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'meta/AUTH_LOGIN_SUCCESS';
