export const LOAD_ACTIVE_VOUCHERS = 'pirania/LOAD_ACTIVE_VOUCHERS';
export const LOAD_ACTIVE_VOUCHERS_SUCCESS = 'pirania/LOAD_ACTIVE_VOUCHERS_SUCCESS';
export const LOAD_ACTIVE_VOUCHERS_ERROR = 'pirania/LOAD_ACTIVE_VOUCHERS_ERROR';

export const LOAD_GOVERNANCE = 'pirania/LOAD_GOVERNANCE';
export const LOAD_GOVERNANCE_SUCCESS = 'pirania/LOAD_GOVERNANCE_SUCCESS';
export const LOAD_GOVERNANCE_ERROR = 'pirania/LOAD_GOVERNANCE_ERROR';

export const LOAD_VOUCHERS = 'pirania/LOAD_VOUCHERS';
export const LOAD_VOUCHERS_SUCCESS = 'pirania/LOAD_VOUCHERS_SUCCESS';
export const LOAD_VOUCHERS_ERROR = 'pirania/LOAD_VOUCHERS_ERROR';

export const CREATE_MEMBER_VOUCHER = 'pirania/CREATE_MEMBER_VOUCHER';
export const CREATE_MEMBER_VOUCHER_SUCCESS = 'pirania/CREATE_MEMBER_VOUCHER_SUCCESS';
export const CREATE_MEMBER_VOUCHER_ERROR = 'pirania/CREATE_MEMBER_VOUCHER_ERROR';

export const CREATE_VISITOR_VOUCHER = 'pirania/CREATE_VISITOR_VOUCHER';
export const CREATE_VISITOR_VOUCHER_SUCCESS = 'pirania/CREATE_VISITOR_VOUCHER_SUCCESS';
export const CREATE_VISITOR_VOUCHER_ERROR = 'pirania/CREATE_VISITOR_VOUCHER_ERROR';

export const RENEW_MEMBER_VOUCHERS = 'pirania/RENEW_MEMBER_VOUCHERS';
export const RENEW_MEMBER_VOUCHERS_SUCCESS = 'pirania/RENEW_MEMBER_VOUCHERS_SUCCESS';
export const RENEW_MEMBER_VOUCHERS_ERROR = 'pirania/RENEW_MEMBER_VOUCHERS_ERROR';

export const DELETE_VOUCHER = 'pirania/DELETE_VOUCHER';
export const DELETE_VOUCHER_SUCCESS = 'pirania/DELETE_VOUCHER_SUCCESS';
export const DELETE_VOUCHER_ERROR = 'pirania/DELETE_VOUCHER_ERROR';
