export const LOAD_GOVERNANCE = 'pirania/LOAD_GOVERNANCE';
export const LOAD_GOVERNANCE_SUCCESS = 'pirania/LOAD_GOVERNANCE_SUCCESS';
export const LOAD_GOVERNANCE_ERROR = 'pirania/LOAD_GOVERNANCE_ERROR';