export const activeVouchers = state => state.pirania.activeVouchers;
export const governance = state => state.pirania.governance;
export const content = state => state.pirania.content;
export const vouchers = state => state.pirania.vouchers;
export const loading = state => state.pirania.loading;
export const createVoucher = state => state.pirania.createVoucher;
export const renewed = state => state.pirania.renewed;
export const status = state => state.pirania.status;
export const governanceWritten = state => state.pirania.governanceWritten;
