export const LOCATION_LOAD = 'ws/LOCATION_LOAD';
export const LOCATION_LOAD_SUCCESS = 'ws/LOCATION_LOAD_SUCCESS';
export const LOCATION_CHANGE = 'ws/LOCATION_CHANGE';
export const LOCATION_CHANGE_SUCCESS = 'ws/LOCATION_CHANGE_SUCCESS';
export const LOCATION_USER_SET = 'ws/LOCATION_USER_SET';